CREATE DATABASE IF NOT EXISTS SITEFODI;

USE SITEFODI;

-- USER

CREATE TABLE USER (
    id INT NOT NULL AUTO_INCREMENT,
    fullname VARCHAR(100) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    user_password VARCHAR(20) NOT NULL,
    isRoot BOOLEAN DEFAULT false,
    PRIMARY KEY (id)
);

DESCRIBE USER;

CREATE TABLE THERAPIST (
    id INT NOT NULL,
    cc VARCHAR(20) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES USER(id)
);
